@anon_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24ifQ.625_WdcF3KHqz5amU0x2X5WWHP-OEs_4qj0ssLNHzTs

@host = http://localhost:54321
@path_functions = /functions/v1/treemap-data
### filter by bezirk
# hauptverwaltung: "Hauptverwaltung",
# pankow: "Pankow",
# reinickendorf: "Reinickendorf",
# steglitz_zehlendorf: "Steglitz-Zehlendorf",
# friedrichshain_kreuzberg: "Friedrichshain-Kreuzberg",
# marzahn_hellersdorf: "Marzahn-Hellersdorf",
# neukoelln: "Neukölln",
# lichtenberg: "Lichtenberg",
# treptow_koepenick: "Treptow-Köpenick",
# tempelhof_schoeneberg: "Tempelhof-Schöneberg",
# spandau: "Spandau",
# mitte: "Mitte",
# charlottenburg_wilmersdorf: "Charlottenburg-Wilmersdorf",




POST {{host}}{{path_functions}}?type=Einnahmetitel&bezirk=mitte
Authorization: Bearer {{anon_token}}
Content-Type: application/json


### filter bei Einnahmetitel (default)
#  response is very large and might take some time

POST {{host}}{{path_functions}}
Authorization: Bearer {{anon_token}}
Content-Type: application/json

### filter bei Ausgabetitel
#  response is very large and might take some time

POST {{host}}{{path_functions}}?type=Ausgabetitel
Authorization: Bearer {{anon_token}}
Content-Type: application/json


###


POST {{host}}/rest/v1/rpc/ftc
Content-Type: application/json
apikey: {{anon_token}}
Authorization: Bearer {{anon_token}}

{ "search": "panke" }
