-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.ftc(
	search character varying)
    RETURNS TABLE(id text, typ text, bezeichnung text, bereich text, bereichs_bezeichnung text, einzelplan text, einzelplan_bezeichnung text, kapitel text, kapitel_bezeichnung text, hauptgruppe text, hauptgruppen_bezeichnung text, obergruppe text, obergruppen_bezeichnung text, gruppe text, gruppen_bezeichnung text, hauptfunktion text, hauptfunktions_bezeichnung text, oberfunktion text, oberfunktions_bezeichnung text, funktion text, funktions_bezeichnung text, titel_art text, titel text, titel_bezeichnung text, jahr text, betrag_typ text, betrag text) 
    LANGUAGE 'plpgsql'
    COST 100
    VOLATILE PARALLEL UNSAFE
    ROWS 1000

AS $BODY$
    begin
    return query
    select h.id ,
    h.typ ,
    h.bezeichnung ,
    h.bereich ,
    h.bereichs_bezeichnung ,
    h.einzelplan ,
    h.einzelplan_bezeichnung ,
    h.kapitel ,
    h.kapitel_bezeichnung ,
    h.hauptgruppe ,
    h.hauptgruppen_bezeichnung ,
    h.obergruppe ,
    h.obergruppen_bezeichnung ,
    h.gruppe ,
    h.gruppen_bezeichnung ,
    h.hauptfunktion ,
    h.hauptfunktions_bezeichnung ,
    h.oberfunktion ,
    h.oberfunktions_bezeichnung ,
    h.funktion ,
    h.funktions_bezeichnung ,
    h.titel_art ,
    h.titel ,
    h.titel_bezeichnung ,
    h.jahr ,
    h.betrag_typ ,
    h.betrag  from haushaltsdaten_2022 h WHERE search_document @@ plainto_tsquery('german', search);
end;
$BODY$;

ALTER FUNCTION public.ftc(character varying)
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.ftc(character varying) TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.ftc(character varying) TO anon;

GRANT EXECUTE ON FUNCTION public.ftc(character varying) TO authenticated;

GRANT EXECUTE ON FUNCTION public.ftc(character varying) TO postgres;

GRANT EXECUTE ON FUNCTION public.ftc(character varying) TO service_role;
