-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
CREATE MATERIALIZED VIEW IF NOT EXISTS public.haushaltsdaten_current TABLESPACE pg_default AS
SELECT
	h."ID" AS id,
	h."Typ" AS typ,
	h."Bezeichnung" AS bezeichnung,
	h."Bereich" AS bereich,
	h."Bereichsbezeichnung" AS bereichs_bezeichnung,
	h."Einzelplan" AS einzelplan,
	h."Einzelplanbezeichnung" AS einzelplan_bezeichnung,
	h."Kapitel" AS kapitel,
	h."Kapitelbezeichnung" AS kapitel_bezeichnung,
	h."Hauptgruppe" AS hauptgruppe,
	h."Hauptgruppenbezeichnung" AS hauptgruppen_bezeichnung,
	h."Obergruppe" AS obergruppe,
	h."Obergruppenbezeichnung" AS obergruppen_bezeichnung,
	h."Gruppe" AS gruppe,
	h."Gruppenbezeichnung" AS gruppen_bezeichnung,
	h."Hauptfunktion" AS hauptfunktion,
	h."Hauptfunktionsbezeichnung" AS hauptfunktions_bezeichnung,
	h."Oberfunktion" AS oberfunktion,
	h."Oberfunktionsbezeichnung" AS oberfunktions_bezeichnung,
	h."Funktion" AS funktion,
	h."Funktionsbezeichnung" AS funktions_bezeichnung,
	h."Titelart" AS titel_art,
	h."Titel" AS titel,
	h."Titelbezeichnung" AS titel_bezeichnung,
	h."Jahr" AS jahr,
	h."BetragTyp" AS betrag_typ,
	h."Betrag" AS betrag,
	to_tsvector('german'::regconfig, (((((((((((((((((((((((((((((((((((((((((((((((((COALESCE(h."Typ", ''::text) || ' '::text) || COALESCE(h."Bezeichnung", ''::text)) || ' '::text) || COALESCE(h."Bereich", ''::text)) || ' '::text) || COALESCE(h."Bereichsbezeichnung", ''::text)) || ' '::text) || COALESCE(h."Einzelplan", ''::text)) || ' '::text) || COALESCE(h."Einzelplanbezeichnung", ''::text)) || ' '::text) || COALESCE(h."Kapitel", ''::text)) || ' '::text) || COALESCE(h."Kapitelbezeichnung", ''::text)) || ' '::text) || COALESCE(h."Hauptgruppe", ''::text)) || ' '::text) || COALESCE(h."Hauptgruppenbezeichnung", ''::text)) || ' '::text) || COALESCE(h."Obergruppe", ''::text)) || ' '::text) || COALESCE(h."Obergruppenbezeichnung", ''::text)) || ' '::text) || COALESCE(h."Gruppe", ''::text)) || ' '::text) || COALESCE(h."Gruppenbezeichnung", ''::text)) || ' '::text) || COALESCE(h."Hauptfunktion", ''::text)) || ' '::text) || COALESCE(h."Hauptfunktionsbezeichnung", ''::text)) || ' '::text) || COALESCE(h."Oberfunktion", ''::text)) || ' '::text) || COALESCE(h."Oberfunktionsbezeichnung", ''::text)) || ' '::text) || COALESCE(h."Funktion", ''::text)) || ' '::text) || COALESCE(h."Funktionsbezeichnung", ''::text)) || ' '::text) || COALESCE(h."Titelart", ''::text)) || ' '::text) || COALESCE(h."Titel", ''::text)) || ' '::text) || COALESCE(h."Titelbezeichnung", ''::text)) || ' '::text) || COALESCE(h."Jahr", ''::text)) || ' '::text) || COALESCE(h."BetragTyp", ''::text)) || ' '::text) || COALESCE(h."Betrag", ''::text)) AS search_document
FROM
	haushaltsdaten_22_23 AS h WITH DATA;

ALTER TABLE IF EXISTS public.haushaltsdaten_current OWNER TO postgres;

GRANT ALL ON TABLE public.haushaltsdaten_current TO authenticated;

GRANT ALL ON TABLE public.haushaltsdaten_current TO postgres;

GRANT ALL ON TABLE public.haushaltsdaten_current TO anon;

GRANT ALL ON TABLE public.haushaltsdaten_current TO service_role;

CREATE OR REPLACE FUNCTION public.ftc (IN search character varying)
	RETURNS TABLE (
		id text,
		typ text,
		bezeichnung text,
		bereich text,
		bereichs_bezeichnung text,
		einzelplan text,
		einzelplan_bezeichnung text,
		kapitel text,
		kapitel_bezeichnung text,
		hauptgruppe text,
		hauptgruppen_bezeichnung text,
		obergruppe text,
		obergruppen_bezeichnung text,
		gruppe text,
		gruppen_bezeichnung text,
		hauptfunktion text,
		hauptfunktions_bezeichnung text,
		oberfunktion text,
		oberfunktions_bezeichnung text,
		funktion text,
		funktions_bezeichnung text,
		titel_art text,
		titel text,
		titel_bezeichnung text,
		jahr text,
		betrag_typ text,
		betrag text)
	LANGUAGE 'plpgsql'
	VOLATILE PARALLEL UNSAFE
	COST 100 ROWS 1000
	AS $BODY$
BEGIN
	RETURN query
	SELECT
		h.id,
		h.typ,
		h.bezeichnung,
		h.bereich,
		h.bereichs_bezeichnung,
		h.einzelplan,
		h.einzelplan_bezeichnung,
		h.kapitel,
		h.kapitel_bezeichnung,
		h.hauptgruppe,
		h.hauptgruppen_bezeichnung,
		h.obergruppe,
		h.obergruppen_bezeichnung,
		h.gruppe,
		h.gruppen_bezeichnung,
		h.hauptfunktion,
		h.hauptfunktions_bezeichnung,
		h.oberfunktion,
		h.oberfunktions_bezeichnung,
		h.funktion,
		h.funktions_bezeichnung,
		h.titel_art,
		h.titel,
		h.titel_bezeichnung,
		h.jahr,
		h.betrag_typ,
		h.betrag
	FROM
		haushaltsdaten_current h
	WHERE
		search_document @@ plainto_tsquery('german', search);
END;
$BODY$;

