-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
CREATE MATERIALIZED VIEW IF NOT EXISTS public.haushaltsdaten_2022 TABLESPACE pg_default AS
SELECT
  haushaltsdaten_22_23."ID" AS id,
  haushaltsdaten_22_23."Typ" AS typ,
  haushaltsdaten_22_23."Bezeichnung" AS bezeichnung,
  haushaltsdaten_22_23."Bereich" AS bereich,
  haushaltsdaten_22_23."Bereichsbezeichnung" AS bereichs_bezeichnung,
  haushaltsdaten_22_23."Einzelplan" AS einzelplan,
  haushaltsdaten_22_23."Einzelplanbezeichnung" AS einzelplan_bezeichnung,
  haushaltsdaten_22_23."Kapitel" AS kapitel,
  haushaltsdaten_22_23."Kapitelbezeichnung" AS kapitel_bezeichnung,
  haushaltsdaten_22_23."Hauptgruppe" AS hauptgruppe,
  haushaltsdaten_22_23."Hauptgruppenbezeichnung" AS hauptgruppen_bezeichnung,
  haushaltsdaten_22_23."Obergruppe" AS obergruppe,
  haushaltsdaten_22_23."Obergruppenbezeichnung" AS obergruppen_bezeichnung,
  haushaltsdaten_22_23."Gruppe" AS gruppe,
  haushaltsdaten_22_23."Gruppenbezeichnung" AS gruppen_bezeichnung,
  haushaltsdaten_22_23."Hauptfunktion" AS hauptfunktion,
  haushaltsdaten_22_23."Hauptfunktionsbezeichnung" AS hauptfunktions_bezeichnung,
  haushaltsdaten_22_23."Oberfunktion" AS oberfunktion,
  haushaltsdaten_22_23."Oberfunktionsbezeichnung" AS oberfunktions_bezeichnung,
  haushaltsdaten_22_23."Funktion" AS funktion,
  haushaltsdaten_22_23."Funktionsbezeichnung" AS funktions_bezeichnung,
  haushaltsdaten_22_23."Titelart" AS titel_art,
  haushaltsdaten_22_23."Titel" AS titel,
  haushaltsdaten_22_23."Titelbezeichnung" AS titel_bezeichnung,
  haushaltsdaten_22_23."Jahr" AS jahr,
  haushaltsdaten_22_23."BetragTyp" AS betrag_typ,
  haushaltsdaten_22_23."Betrag" AS betrag
FROM
  haushaltsdaten_22_23
WHERE
  haushaltsdaten_22_23."Jahr" = '2022'::text WITH DATA;

ALTER TABLE IF EXISTS public.haushaltsdaten_2022 OWNER TO postgres;

GRANT ALL ON TABLE public.haushaltsdaten_2022 TO authenticated;

GRANT ALL ON TABLE public.haushaltsdaten_2022 TO postgres;

GRANT ALL ON TABLE public.haushaltsdaten_2022 TO anon;

GRANT ALL ON TABLE public.haushaltsdaten_2022 TO service_role;

