-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.haushaltsdaten_22_23
(
    "ID" text COLLATE pg_catalog."default",
    "Typ" text COLLATE pg_catalog."default",
    "Bezeichnung" text COLLATE pg_catalog."default",
    "Bereich" text COLLATE pg_catalog."default",
    "Bereichsbezeichnung" text COLLATE pg_catalog."default",
    "Einzelplan" text COLLATE pg_catalog."default",
    "Einzelplanbezeichnung" text COLLATE pg_catalog."default",
    "Kapitel" text COLLATE pg_catalog."default",
    "Kapitelbezeichnung" text COLLATE pg_catalog."default",
    "Hauptgruppe" text COLLATE pg_catalog."default",
    "Hauptgruppenbezeichnung" text COLLATE pg_catalog."default",
    "Obergruppe" text COLLATE pg_catalog."default",
    "Obergruppenbezeichnung" text COLLATE pg_catalog."default",
    "Gruppe" text COLLATE pg_catalog."default",
    "Gruppenbezeichnung" text COLLATE pg_catalog."default",
    "Hauptfunktion" text COLLATE pg_catalog."default",
    "Hauptfunktionsbezeichnung" text COLLATE pg_catalog."default",
    "Oberfunktion" text COLLATE pg_catalog."default",
    "Oberfunktionsbezeichnung" text COLLATE pg_catalog."default",
    "Funktion" text COLLATE pg_catalog."default",
    "Funktionsbezeichnung" text COLLATE pg_catalog."default",
    "Titelart" text COLLATE pg_catalog."default",
    "Titel" text COLLATE pg_catalog."default",
    "Titelbezeichnung" text COLLATE pg_catalog."default",
    "Jahr" text COLLATE pg_catalog."default",
    "BetragTyp" text COLLATE pg_catalog."default",
    "Betrag" text COLLATE pg_catalog."default"
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.haushaltsdaten_22_23
    OWNER to postgres;

GRANT ALL ON TABLE public.haushaltsdaten_22_23 TO anon;

GRANT ALL ON TABLE public.haushaltsdaten_22_23 TO authenticated;

GRANT ALL ON TABLE public.haushaltsdaten_22_23 TO postgres;

GRANT ALL ON TABLE public.haushaltsdaten_22_23 TO service_role;
